#!/bin/sh
imagesize="`file $2 | rev | cut -d ' ' -f 1-3 | rev`"
filesize="`du -h $2 | cut -f 1`"
palette="/tmp/palette.png"
filters="fps=10,scale=$3:-1:flags=lanczos"

if [ "$#" == "0" ]; then
	echo "Usage: `basename $0` [inputfile outputfile imagesize compression]"
	echo "Eg: `basename $0` cat.mp4 cat.gif 400 80"
  exit 0
fi

echo "Converting Video to GIF......."
ffmpeg -loglevel panic -i $1 -vf "$filters,palettegen=stats_mode=diff" -y $palette
ffmpeg -loglevel panic -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
rm $palette
echo "Optimizing GIF......."
gifsicle -O3 --lossy=$4 -o output.gif $2
mv output.gif $2
echo "Finished!"
echo " "
echo "$2 image size is $imagesize and file size is $filesize"
