#!/bin/sh
palette="/tmp/palette.png"
filters="fps=10,scale=$3:-1:flags=lanczos"

if [ "$#" == "0" ]; then
	echo "Usage: `basename $0` [inputfile outputfile imagesize compression]"
	echo "Eg: `basename $0` cat.mp4 cat.gif 400 80"
#	echo "(400:-1 = width 400 x auto height (-1:400 = auto height x 400 width)" 
  exit 0
fi

ffmpeg -v warning -i $1 -vf "$filters,palettegen=stats_mode=diff" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
rm $palette
gifsicle -O3 --lossy=$4 -o output.gif $2
mv output.gif $2
